### ISSUE TITLE
a need sdk for xamarin forms ios and android

### ISSUE THREAD

**Issue by saimon85** [GetMetaMap/metamap-mobile-examples#1]
Hello, I am currently working with xamarin Forms and I would like to consume the ios and android sdk, but I cannot create the binding. Can you support me with sdk for xamarin forms please.

**Comment by aposnovmati** [comment]
Hello, we not support xamarin, but xamarin support native sdk's, so you can write some small bridge related to native documentation iOS SDK https://github.com/GetMetaMap/mati-ios-sdk, android SDK https://github.com/GetMetaMap/metamap-android-sdk 

we have old version as example https://drive.google.com/file/d/1Y2LvKzMGlqlBb1nKOqd_M_FrDrLNhR0H/view?usp=sharing
